---
# QA執行流程 - AI處理的結構化工作流程
# 版本：2.0（YAML格式）
# 目的：具有5個核心階段的證據驅動實施審查

metadata:
  name: "QA執行流程"
  version: "2.0"
  format: "yaml"
  target_audience: "AI代理"
  description: "全面實施審查的結構化工作流程"
  
overview:
  description: "Evidence-driven implementation review with 5 core stages"
  report_template: "~/.claude/templates/review-tmpl.yaml"
  stages:
    - id: 1
      name: "初始化和证据收集"
      description: "Load workflow, gather all implementation evidence"
    - id: 2
      name: "范围和合规性分析"
      description: "Verify scope alignment and requirements conformance"
    - id: 3
      name: "质量评估"
      description: "Assess implementation against 7-dimension quality framework"
    - id: 4
      name: "问题发现和建议"
      description: "Identify issues, rank by severity, propose actionable fixes"
    - id: 5
      name: "报告生成/更新+验证"
      description: "Generate/update template-compliant report and handle task completion"
    - id: 6
      name: "更新任務文件"
      description: "根據審查結果更新 task.md"

execution_protocol:
  enforcement_compliance:
    mandatory_enforcement_file: "~/.claude/core/task-reviewer-enforcement.md"
    note: "All detailed enforcement rules, validation criteria, and quality standards are defined in the enforcement file"

stages:
  stage_1:
    id: 1
    name: "初始化和证据收集"
    name_en: "Initialize & Collect Evidence"
    objectives:
      - "Determine review mode (initial vs follow-up)"
      - "Gather all required implementation evidence"
      - "Set review scope and focus areas"
    
    actions:
      file_checks:
        - tool: "glob_file_search"
          pattern: "{task_id}-review.*"
          location: "docs/implementation-review/"
          purpose: "Check existing review documents"
          
      spec_gathering:
        - tool: "glob_file_search"
          pattern: ".kiro/specs/**"
          purpose: "Discover all specification files under .kiro/specs/"
        - tool: "read_file"
          files: "<from previous glob_file_search>"
          purpose: "Gather specification sources (all .kiro/specs/**)"
        - tool: "read_file"
          files:
            - ".kiro/specs/task.md"
            - ".kiro/specs/requirements.md"
            - ".kiro/specs/design.md"
          purpose: "Ensure core specs explicitly loaded"
          
      plan_discovery:
        - tool: "glob_file_search"
          pattern: "{task_id}-plan.*"
          location: "docs/implementation-plan/"
          purpose: "Find implementation plan"
        - tool: "read_file"
          file: "located implementation plan"
          purpose: "Extract notes for cross-reference based on mode"
          mode_condition: "initial -> dev_notes only; follow-up (brownfield) -> re_dev_notes only; never mix"
          focus_initial: ["dev_notes"]
          focus_brownfield: ["re_dev_notes"]
          
      implementation_analysis:
        - tool: "codebase_search"
          query: "Where are the main implementation changes for this task?"
          purpose: "Identify implementation changes"
        - tool: "grep"
          pattern: "{task_id}"
          output_mode: "files_with_matches"
          purpose: "Find task-related files"
          
      quality_artifacts:
        - tool: "glob_file_search"
          pattern: "*test*"
          purpose: "Find test files and reports"
        - tool: "grep"
          pattern: "coverage|CI|build"
          purpose: "Find quality metrics"
    
    follow_up_mode:
      additional_actions:
        - "Read previous review document"
        - "Extract previous findings for tracking"
        - "Identify remediation scope and focus areas"
      
      brownfield_specific:
        - tool: "read_file"
          file: "implementation plan with re_dev_notes"
          purpose: "Check for re-development notes"
          action: "Read re_dev_notes section if present"
        - policy_enforcement:
          - "In brownfield mode, IGNORE dev_notes completely"
          - "Use only re_dev_notes and all .kiro/specs/** documents as sources"
        
        - re_dev_notes_verification:
          critical_validations:
            - action: "Verify root cause analysis accuracy"
              method: "Cross-reference identified root causes with actual code/architecture issues"
              evidence_required: "Technical analysis, code review findings, performance data"
            
            - action: "Validate re-development strategy execution"
              method: "Compare planned re-dev strategy with actual implementation approach"
              evidence_required: "Implementation approach documentation, architectural decisions"
            
            - action: "Confirm quality improvement measures"
              method: "Verify documented quality improvements are actually implemented and effective"
              evidence_required: "Before/after metrics, test coverage reports, security scan results"
            
            - action: "Assess iteration context understanding"
              method: "Validate re-dev trigger causes against review history and failure points"
              evidence_required: "Previous review reports, failure analysis, stakeholder feedback"
          
          iteration_tracking:
            - "Verify iteration_number matches actual re-development cycle"
            - "Confirm trigger_reason aligns with documented failure/feedback"
            - "Validate learning capture from previous iterations"
        
        - focus_adjustment: "Adjust review focus based on re-dev iteration and previous failures"
    
    validation_checkpoint:
      - "Review mode determined (initial/follow-up)"
      - "All spec files read"
      - "Implementation plan located"
      - "Implementation evidence gathered"
      - "Quality artifacts collected"
      - "Re-dev notes reviewed (if present in brownfield scenarios)"
      - "Dev_notes ignored in brownfield (no references used)"

  stage_2:
    id: 2
    name: "范围和合规性分析"
    name_en: "Scope & Conformance Analysis"
    objectives:
      - "Verify implementation matches planned scope"
      - "Check requirements conformance"
      - "Document any scope deviations"
    
    actions:
      scope_analysis:
        - tool: "codebase_search"
          query: "What functionality was actually implemented for this task?"
          purpose: "Analyze scope alignment"
          
      requirements_verification:
        - tool: "codebase_search"
          query: "How do the implemented changes meet the stated requirements?"
          purpose: "Verify requirements satisfaction"
        - cross_reference_analysis:
          initial_mode:
            dev_notes_verification:
              - action: "Compare dev_notes.detailed_changes against actual code changes"
                method: "Line-by-line diff analysis between documented and implemented changes"
                evidence_required: "File paths, line numbers, commit hashes"
              
              - action: "Verify F-IDs and N-IDs mapping accuracy"
                method: "Cross-reference functional/non-functional requirement IDs in dev_notes with actual implementation"
                evidence_required: "Requirement traceability matrix"
              
              - action: "Validate dev_notes quality metrics against measured results"
                method: "Compare documented performance/security/test metrics with actual measurements"
                evidence_required: "Test reports, performance benchmarks, security scan results"
              
              - action: "Check dev_notes deviations against observed implementation"
                method: "Verify documented scope deviations match actual implementation scope"
                evidence_required: "Scope comparison analysis with justification"
          brownfield_mode:
            re_dev_notes_verification:
              - action: "Compare re_dev_notes planned/remediation changes against actual code changes"
                method: "Line-by-line diff analysis between documented remediation plan and implemented changes"
                evidence_required: "File paths, line numbers, commit hashes"
              
              - action: "Verify F-IDs and N-IDs mapping accuracy (based on re_dev_notes and specs)"
                method: "Cross-reference functional/non-functional requirement IDs in re_dev_notes with implementation and .kiro/specs/**"
                evidence_required: "Requirement traceability matrix"
              
              - action: "Validate re_dev_notes quality metrics against measured results"
                method: "Compare documented performance/security/test metrics in re_dev_notes with actual measurements"
                evidence_required: "Test reports, performance benchmarks, security scan results"
              
              - action: "Enforce policy to IGNORE dev_notes in brownfield"
                method: "Ensure no dev_notes references are used as evidence or inputs"
                evidence_required: "Review reasoning trace and cited sources"
          
          consistency_validation:
            critical_checks:
              - "Developer claims vs actual implementation"
              - "Documented challenges vs code solutions"
              - "Claimed quality metrics vs measured results"
              - "Stated deviations vs implementation evidence"
            failure_escalation: "Inconsistencies treated as severe credibility issues requiring immediate investigation"
          
      deviation_assessment:
        tasks:
          - "Cross-reference scope vs implementation"
          - "Document scope violations with evidence"
          - "Assess deviation impact"
    
    follow_up_mode:
      additional_actions:
        - "Verify previous scope violations resolved"
        - "Check for new scope deviations"
    
    validation_checkpoint:
      - "Scope analysis completed"
      - "Requirements conformance checked"
      initial_mode:
        - "Dev_notes detailed_changes verified against actual code"
        - "F-IDs and N-IDs mapping accuracy confirmed"
        - "Quality metrics cross-validated (documented vs measured)"
        - "Developer claims consistency checked"
      brownfield_mode:
        - "Re_dev_notes remediation/changes verified against actual code"
        - "Iteration context validated"
        - "Root cause analysis accuracy verified"
        - ".kiro/specs/** cross-referenced against implementation"
        - "Dev_notes ignored (no references used)"
      - "Deviations documented with evidence"
      - "Impact assessment done"

  stage_3:
    id: 3
    name: "质量评估"
    name_en: "Quality Assessment"
    objectives:
      - "Evaluate implementation against 7-dimension quality framework"
      - "Score each dimension (1-5) with detailed justification"
      - "Gather quantitative metrics"
    
    quality_dimensions:
      code_quality:
        name: "Code Quality"
        actions:
          - tool: "codebase_search"
            query: "How readable and maintainable is the implemented code?"
          - tool: "grep"
            pattern: "error|exception|catch|handle"
            purpose: "Review error handling"
            
      security:
        name: "Security Review"
        actions:
          - tool: "codebase_search"
            query: "How are authentication and authorization handled in this implementation?"
          - tool: "grep"
            pattern: "password|secret|token|key|auth"
            purpose: "Find security-sensitive code"
            
      performance:
        name: "Performance Review"
        actions:
          - tool: "codebase_search"
            query: "What are the performance implications of this implementation?"
            
      testing:
        name: "Testing Review"
        actions:
          - tool: "glob_file_search"
            pattern: "*test*"
          - tool: "grep"
            pattern: "describe|it|test|spec"
            purpose: "Analyze test coverage"
            
      documentation:
        name: "Documentation Review"
        actions:
          - tool: "glob_file_search"
            patterns:
              - "README*"
              - "*doc*"
              
      maintainability:
        name: "Maintainability"
        evaluation_focus:
          - "Code structure and organization"
          - "Dependency management"
          - "Configuration management"
          
      deployment:
        name: "Deployment & Operations"
        evaluation_focus:
          - "Deployment process"
          - "Monitoring and logging"
          - "Production readiness"
    
    follow_up_mode:
      additional_actions:
        - "Compare current vs previous quality metrics"
        - "Calculate score deltas and identify trends"
        - "Verify previous quality issues resolved"
    
    validation_checkpoint:
      - "All 7 dimensions assessed with scores"
      - "Each score justified with evidence"
      - "Quantitative metrics collected"
      - "Trend analysis completed (for follow-up)"

  stage_4:
    id: 4
    name: "问题发现和建议"
    name_en: "Findings & Recommendations"
    objectives:
      - "Compile all identified issues"
      - "Rank findings by severity (blocker/high/medium/low)"
      - "Propose actionable recommendations with success criteria"
    
    finding_categories:
      - "Scope violations"
      - "Quality issues"
      - "Security concerns"
      - "Performance problems"
      - "Test gaps"
      - "Documentation issues"
    
    severity_levels:
      blocker:
        description: "Critical issues that prevent deployment"
        requires_immediate_action: true
      high:
        description: "Major issues that significantly impact functionality"
        requires_action_before_release: true
      medium:
        description: "Issues that should be addressed soon"
        can_be_scheduled: true
      low:
        description: "Minor improvements or suggestions"
        optional: true
    
    recommendation_structure:
      - "Specific remediation steps"
      - "Measurable success criteria"
      - "Priority and timeline"
      - "Resource requirements"
    
    follow_up_mode:
      additional_actions:
        - "Mark resolved findings"
        - "Update remaining findings status"
        - "Identify new findings"
        - "Track remediation progress"
    
    validation_checkpoint:
      - "All findings compiled and ranked"
      - "Recommendations are actionable"
      - "Success criteria defined"
      - "Evidence provided for each finding"

  stage_5:
    id: 5
    name: "报告生成和验证"
    name_en: "Report Generation & Validation"
    objectives:
      - "Generate template-compliant review report"
      - "Validate document completeness"
      - "Handle task completion based on QA decision"
    
    report_generation:
      initial_review:
        tasks:
          - "Populate all template sections"
          - "Ensure no placeholder values remain"
          - "Include all evidence links"
          
      follow_up_review:
        tasks:
          - "Update existing document sections"
          - "Preserve metadata/context/appendix"
          - "Add trend analysis and remediation tracking"
          
      output_location: "{project_root}/docs/implementation-review/{task_id}-review.md"
    
    qa_decision_handling:
      analysis_steps:
        - "Extract QA decision (pass/fail)"
        - "Identify blocking issues"
        - "Set internal variable: final_review_status"
        
      if_review_passes:
        actions:
          - "Set final_review_status to 'pass'"
          
      if_review_fails:
        actions:
          - "Set final_review_status to 'fail'"
    
    final_validation:
      checks:
        - tool: "read_file"
          target: "generated review document"
          validations:
            - "Compare against template structure"
            - "Verify no placeholders remain"
            - "Confirm evidence links valid"
            - "Validate markdown formatting"
    
    validation_checkpoint:
      - "Report generated and saved"
      - "Template compliance verified"
      - "QA decision extracted and status variable set"
      - "Final validation passed"

  stage_6:
    id: 6
    name: "更新任務文件"
    name_en: "Update Task Document"
    depends_on: [5]
    objectives:
      - "根據最終審查狀態更新 task.md"
      - "確保任務狀態在中央文件中得到準確反映"
    
    actions:
      - tool: "edit_file"
        target: ".kiro/specs/task.md"
        purpose: "根據審查結果更新任務狀態"
        condition: "on_variable_value"
        variable_name: "final_review_status"
        
        on_value:
          pass:
            action_type: "search_and_replace"
            search_pattern: "- [ ] {task_title}"
            replace_pattern: "- [x] {task_title}"
            search_pattern_alt: "- [-] {task_title}"
            replace_pattern_alt: "- [x] {task_title}"

          fail:
            action_type: "search_and_replace"
            search_pattern: "- [ ] {task_title}"
            replace_pattern: "- [-] {task_title}"

    validation_checkpoint:
      - "task.md 文件已根據審查結果更新"
      - "最終任務狀態已正確標記"

critical_success_factors:
  mandatory_requirements:
    evidence_based:
      description: "Every conclusion supported by concrete evidence"
      includes:
        - "File paths"
        - "PR links"
        - "Measurements"
        - "Code references"
        
    sequential_execution:
      description: "Complete stages in order, validate at each checkpoint"
      enforcement: "Stop immediately if validation fails"
      
    template_compliance:
      description: "Follow template structure exactly, populate all sections"
      validation_required: true
      
    no_placeholders:
      description: "Replace all placeholder values with actual content"
      validation_required: true
      
    task_authority:
      description: "QA has final authority on task completion"
      authority_level: "final"

  error_handling:
    validation_failure_protocol:
      steps:
        - "STOP immediately"
        - "Identify specific failure"
        - "Return to appropriate stage"
        - "Re-execute with corrections"
        - "Re-validate before proceeding"

  quality_gates:
    requirements:
      - "All stages completed sequentially"
      - "All evidence collected and documented"
      - "All template sections populated"
      - "All validation checkpoints passed"
      - "Document ready for stakeholder review"
    
    success_criteria: "Comprehensive, evidence-based review report that enables informed decisions"

# Tool Integration Guidelines
tool_usage_patterns:
  file_operations:
    read_file: "Use for reading specific known files"
    glob_file_search: "Use for pattern-based file discovery"
    list_dir: "Use for directory exploration"
    
  code_analysis:
    codebase_search: "Use for semantic code understanding"
    grep: "Use for pattern matching and exact text search"
    
  documentation:
    write: "Use for generating final reports"
    search_replace: "Use for updating existing documents"

# AI Processing Notes
ai_optimization:
  structured_format: "YAML enables better parsing and validation"
  clear_hierarchy: "Nested structure maps to AI decision trees"
  tool_integration: "Explicit tool calls reduce AI confusion"
  validation_points: "Checkpoints enable early error detection"
  follow_up_support: "Separate handling for iterative reviews"
