---
# Backend Developer 工作流程
# 專為後端開發者設計的計劃驅動工作流程
template: backend-developer-workflow
version: 2.0

workflow:
  name: "Backend Developer 計劃驅動工作流程"
  description: "專為後端開發者設計的工作流程，專注於伺服器架構、API設計和系統可擴展性"
  enforcement_level: "lenient"
  halt_on_validation_failure: false
  default_profile: "fast_strict"

# === 輸入定義 ===
inputs:
  task_id: "<required>"
  plan_path: "<auto>"
  project_root: "<auto>"
  developer_type: "backend"

# === 計劃解析配置 ===
plan_resolution:
  find_by_task_id: true
  search_paths:
    - "{{project_root}}/docs/implementation-plan"
  supported_extensions:
    - "yaml"
    - "yml" 
    - "md"
  expectations:
    template: "implementation-plan"
    version: 1

# === 範圍管控 ===
guardrails:
  scope_source: "scope"
  out_of_scope_is_blocking: false
  on_scope_violation: "record_warning_and_continue"

# === 前置條件 ===
preconditions:
  - "計劃文件存在於docs/implementation-plan/*並匹配task_id"
  - "計劃範本版本 == 1"
  - "metadata包含task_id、project_name、owner、date"
  - "sources路徑解析"
  - "assumptions和constraints已確認"

# === 執行協議 ===
execution_protocol:
  
  enforcement_compliance:
    mandatory_enforcement_file: "/Users/tszkinlai/Coding/AI workflow/core/dev/enforcement/backend-developer-enforcement.md"
    note: "所有詳細的強制執行規則、驗證標準和執行要求都在後端強制執行文件中定義"

output_contracts:
  objectives: { $ref: "#/schemas/objectives_v1" }
  modules: { $ref: "#/schemas/modules_v1" }

schemas:
  objectives_v1:
    $id: "schemas/objectives_v1"
    type: object
    required: ["F-IDs", "N-IDs", "acceptance_criteria"]
    properties:
      F-IDs:
        type: array
        items:
          type: string
          pattern: "^F-[0-9]+$"
        minItems: 1
      N-IDs:
        type: array
        items:
          type: string
          pattern: "^N-[0-9]+$"
      acceptance_criteria:
        type: array
        items:
          type: object
          required: ["F-ID", "criteria"]
          properties:
            F-ID:
              type: string
              pattern: "^F-[0-9]+$"
            criteria:
              type: array
              items:
                type: string
        minItems: 1
    additionalProperties: false

  modules_v1:
    $id: "schemas/modules_v1"
    type: object
    required: ["modules"]
    properties:
      modules:
        type: array
        items:
          type: object
          required: ["name", "interfaces"]
          properties:
            name:
              type: string
            interfaces:
              type: array
              items:
                type: object
                required: ["name", "methods"]
                properties:
                  name:
                    type: string
                  methods:
                    type: array
                    items:
                      type: object
                      required: ["name", "inputs", "outputs"]
                      properties:
                        name: { type: string }
                        inputs:
                          type: array
                          items:
                            type: object
                        outputs:
                          type: object
            reuse:
              type: array
              items:
                type: string
    additionalProperties: false

# === 階段定義 ===
# 詳細的驗證規則和品質標準在backend enforcement文件中定義
validation_rules:
  note: "詳細的驗證規則和品質標準定義在後端強制執行檔案中"
  
  stage_sequence:
    - workflow_initialization
    - scope_comprehension
    - objectives_and_acceptance
    - architecture_and_modules
    - tdd_cycle_planning
    - tests_first
    - implementation
    - quality_gates
    - milestones_timeline
    - dependencies
    - estimation_tracking
    - risks_changes
    - definition_of_done

  error_handling:
    validation_errors:
      missing_stage:
        severity: "warning"
        message: "強制階段未完成"
        action: "append_warning_and_continue"
      
      scope_violation:
        severity: "warning"
        message: "實作超出定義範圍"
        action: "append_warning_and_continue"
      
      missing_tests:
        severity: "warning"
        message: "實作前未撰寫測試"
        action: "append_warning_and_continue"
      
      tdd_violation:
        severity: "warning"
        message: "違反TDD循環 - 應先撰寫測試"
        action: "append_warning_and_continue"

  format_contracts:
    - stage: "objectives_and_acceptance"
      must_validate_against: "objectives"
      on_failure: "append_warning_and_continue"
    - stage: "architecture_and_modules"
      must_validate_against: "modules"
      on_failure: "append_warning_and_continue"
    - stage: "tdd_cycle_planning"
      must_validate_against: "tdd_plan"
      on_failure: "append_warning_and_continue"

# === 工作流程階段 ===
stages:
  - id: "workflow_initialization"
    title: "工作流程初始化"
    mandatory: true
    validation_checkpoint: true
    actions:
      - load: ["/Users/tszkinlai/Coding/AI workflow/core/dev/workflow/backend-developer-workflow.yaml"]
      - detect_developer_type: "backend"
      - resolve_plan_by_task_id: true
      - verify_preconditions: true

  - id: "scope_comprehension"
    title: "範圍理解"
    mandatory: true
    validation_checkpoint: true
    actions:
      - read: ["context.summary", "context.background", "context.goals"]
      - copy_to_notes: ["context.goals"]
      - review: ["scope.in_scope", "scope.out_of_scope"]
      - check_for_existing_implementation:
          - scan_codebase_for_related_changes: true
          - identify_existing_patterns_and_dependencies: true
          - understand_current_implementation_state: true
          - note_potential_conflicts_with_current_scope: true

  - id: "objectives_and_acceptance"
    title: "目標與驗收"
    mandatory: true
    validation_checkpoint: true
    actions:
      - extract_functional_objectives_as: "F-IDs"
      - extract_non_functional_objectives_as: "N-IDs"
      - attach_acceptance_criteria: true

  - id: "architecture_and_modules"
    title: "架構與模組"
    mandatory: true
    validation_checkpoint: true
    actions:
      - read: ["approach.architecture_overview"]
      - for_each: "approach.modules"
        do:
          - define_first: "interfaces"
          - identify: "reuse"
          - create: "module_skeletons_with_feature_flags"

  - id: "tdd_cycle_planning"
    title: "TDD循環規劃"
    mandatory: true
    validation_checkpoint: true
    actions:
      - plan_tdd_cycles_per: "F-IDs"
      - define_test_scenarios_for_each: "acceptance_criteria"
      - identify_test_data_requirements: true
      - plan_mock_and_stub_strategies: true
      - define_test_environment_setup: true
      - create_tdd_iteration_plan: true

  - id: "tests_first"
    title: "測試優先 (TDD紅階段)"
    mandatory: true
    validation_checkpoint: true
    actions:
      - 🚨_TDD_MANDATORY: "實作前必須先撰寫測試"
      - unit_tests_per_module_aligned_to: "F-IDs"
      - integration_tests_for: ["interfaces", "routing", "api_flows", "failure_paths"]
      - acceptance_tests_mirroring: "acceptance_criteria_per_F-ID"
      - contract_tests_for: ["api_contracts", "service_interfaces"]
      - ensure_tests_fail_initially: "TDD紅階段"
      - document_test_behavior_expectations: true
      - create_test_data_fixtures: true

  - id: "implementation"
    title: "實作 (TDD綠階段)"
    mandatory: true
    validation_checkpoint: true
    actions:
      - 🚨_TDD_ENFORCEMENT: "實作最少程式碼以通過測試"
      - implement_handlers_and_components_per: ["interfaces", "F-IDs"]
      - run_tests_after_each_change: "保持測試綠燈"
      - draft_idempotent_reversible_migrations: true
      - define_ordered_steps_and_backout: true
      - run_in_non_prod_first: true
      - implement_authentication_authorization: true
      - validate_input_sanitization: true
      - ensure_proper_error_handling: true
      - meet_latency_throughput_memory_targets: true
      - implement_proper_logging_monitoring: true
      - enforce_constraints: true
      - traceability:
          reference_task_id: "metadata.task_id"
          in: ["PR_titles", "commits", "code_annotations"]

  - id: "quality_gates"
    title: "品質門檻 (TDD重構階段)"
    mandatory: true
    validation_checkpoint: true
    actions:
      - 🚨_TDD_REFACTOR: "在保持測試綠燈的情況下重構"
      - ensure: "coverage_and_static_analysis_thresholds >= quality_gates"
      - validate_non_functional: "N-IDs_measurements"
      - security_checks: ["dependencies", "SAST", "api_security_audit"]
      - performance_testing: ["latency", "throughput", "memory_usage"]
      - refactor_code_while_maintaining_behavior: true
      - improve_code_structure_and_readability: true
      - eliminate_code_duplication: true
      - optimize_performance_without_breaking_tests: true

  - id: "milestones_timeline"
    title: "里程碑與時程"
    mandatory: true
    validation_checkpoint: true
    actions:
      - map_dev_tasks_to: "milestones.schedule"
      - mark_done_when: "milestones.done_definition_satisfied"

  - id: "dependencies"
    title: "依賴項"
    mandatory: true
    validation_checkpoint: true
    actions:
      - verify_versions_and_SLAs: "dependencies.external"
      - coordinate_internal_owners: "dependencies.internal"

  - id: "estimation_tracking"
    title: "估算與追蹤"
    mandatory: true
    validation_checkpoint: true
    actions:
      - report_progress_using: "estimation.method"
      - keep_remaining_effort_per_work_item: true
      - update_confidence_against: "estimation.summary.confidence"

  - id: "risks_changes"
    title: "風險與變更"
    mandatory: true
    validation_checkpoint: true
    actions:
      - review_weekly: "risks"
      - on_realized_risk: ["execute_mitigation", "then_contingency"]
      - on_scope_creep: "open_question_and_pause"

  - id: "definition_of_done"
    title: "完成定義"
    mandatory: true
    validation_checkpoint: true
    actions:
      - require: [
          "all_F-IDs_pass_acceptance_tests",
          "all_N-IDs_verified_by_measurement",
          "no_unresolved_open_questions",
          "PRs_merged_CI_green"
        ]

# 後端專業化需求現在定義在backend-developer-enforcement.md中
# 這確保了工作流程程序和強制執行規則之間的清楚分離

# === 關鍵成功因素 ===
critical_success_factors:
  - "首先讀取工作流程和計劃檔案 - 絕不在沒有它們的情況下開始"
  - "保持在範圍邊界內 - 對任何範圍問題暫停"
  - "將目標提取為F-IDs和N-IDs - 維持可追溯性"
  - "🚨 TDD強制要求：實作前先撰寫測試 - 紅階段優先"
  - "🚨 TDD強制執行：實作最少程式碼以通過測試 - 綠階段"
  - "🚨 TDD重構：在保持測試綠燈的情況下重構 - 重構階段"
  - "首先定義介面和架構 - 遵循計劃結構"
  - "維持可追溯性 - 在PR、提交、程式碼中包含task_id"
  - "達到品質門檻 - 覆蓋率、靜態分析、效能、安全性"
  - "遵循里程碑和時程 - 準確追蹤進度"
  - "管理風險和依賴項 - 與負責人協調"
  - "完成完成定義 - 所有標準必須滿足"
  - "絕不跳過TDD循環 - 必須先撰寫測試"
  - "在整個實作過程中保持測試綠燈 - TDD安全原則"

# === 工作流程違規回應 ===
workflow_violation_responses:
  - "缺少階段執行：附加警告並繼續"
  - "範圍違規：附加警告並繼續；非同步開啟問題"
  - "計劃偏離：附加警告；記錄決定"
  - "🚨 TDD違規：嚴重警告 - 必須在實作前撰寫測試"
  - "缺少測試：附加警告；在下次迭代中優先修復"
  - "品質門檻失敗：附加警告；包含測量和修復計劃"
  - "缺少可追溯性：附加警告；事後添加task_id參考"
  - "🚨 TDD循環不完整：附加警告；確保完成紅-綠-重構循環"
