---
# Reviewer Orchestrator 工作流程
# 版本：1.0（YAML格式）
# 目的：Dr. Thompson統籌專業reviewer團隊進行並行審查

metadata:
  name: "Reviewer Orchestrator 工作流程"
  version: "1.0"
  format: "yaml"
  target_audience: "Dr. Thompson - QA統帥"
  description: "專業reviewer團隊協調與並行審查工作流程"
  
overview:
  description: "Dr. Thompson統籌專業reviewer團隊進行全面品質審查"
  report_template: "/Users/tszkinlai/Coding/AI workflow/core/qa/templates/review-tmpl.yaml"
  stages:
    - id: 1
      name: "任務分析與團隊組建"
      description: "Analyze task type and assemble professional reviewer team"
    - id: 2
      name: "並行審查執行"
      description: "Execute parallel review by professional reviewers"
    - id: 3
      name: "結果收集與整合"
      description: "Collect and integrate all reviewer results"
    - id: 4
      name: "最終品質判斷"
      description: "Dr. Thompson makes final quality decision"
    - id: 5
      name: "報告生成與維護"
      description: "Generate and maintain final review report"
    - id: 6
      name: "任務狀態更新"
      description: "Update task status based on review result"

execution_protocol:
  enforcement_compliance:
    mandatory_enforcement_file: "/Users/tszkinlai/Coding/AI workflow/core/qa/enforcement/reviewer-orchestrator-enforcement.md"
    unified_enforcement_file: "/Users/tszkinlai/Coding/AI workflow/core/qa/enforcement/task-reviewer-enforcement.md"
    note: "All detailed enforcement rules, validation criteria, and quality standards are defined in the enforcement files"
  
execution_context:
  path_resolution:
    project_root: "{project_root}"
    fallback_order:
      enforcement_file:
        - "/Users/tszkinlai/Coding/AI workflow/core/qa/enforcement/reviewer-orchestrator-enforcement.md"
        - "core/qa/enforcement/reviewer-orchestrator-enforcement.md"
      workflow_file:
        - "/Users/tszkinlai/Coding/AI workflow/core/qa/workflow/reviewer-orchestrator-workflow.yaml"
        - "core/qa/workflow/reviewer-orchestrator-workflow.yaml"
      unified_workflow:
        - "/Users/tszkinlai/Coding/AI workflow/core/qa/workflow/unified-review-workflow.yaml"
        - "core/qa/workflow/unified-review-workflow.yaml"
      report_template:
        - "/Users/tszkinlai/Coding/AI workflow/core/qa/templates/review-tmpl.yaml"
        - "core/qa/templates/review-tmpl.yaml"
      specs_root:
        - "docs/specs/"
        - "specs/"
  
  timeboxes:
    note: "Reference reviewer-orchestrator-enforcement.md for detailed timebox specifications"
    reference_file: "/Users/tszkinlai/Coding/AI workflow/core/qa/enforcement/reviewer-orchestrator-enforcement.md"
    
  failure_policy:
    on_missing_primary_path: "Use fallback order; if none available, append_warning_and_continue_with_limitations"

stages:
  stage_1:
    id: 1
    name: "任務分析與團隊組建"
    name_en: "Task Analysis & Team Assembly"
    objectives:
      - "從 `docs/specs/task.md` 中抽取 `task_id`"
      - "根據 `project_root/docs/implementation-plan/{task_id}-plan.md(如`1-plan.md`, `2-plan.md`, `3-plan.md`...)` 分析任務類型和複雜度"
      - "組建專業reviewer團隊"
      - "確定審查策略和範圍"
    
    actions:
      task_analysis:
        - tool: "codebase_search"
          query: "What type of task is this? API development, frontend UI, database migration, etc."
          purpose: "Determine task type for reviewer selection"
          
      existing_review_check:
        - tool: "glob_file_search"
          pattern: "{task_id}-review.*"
          location: "docs/implementation-review/"
          purpose: "Check if this is initial or follow-up review"
          
      spec_gathering:
        - tool: "read_file"
          files:
            - "docs/specs/task.md"
            - "docs/specs/requirements.md"
            - "docs/specs/design.md"
          purpose: "Understand task requirements and scope"
          
      team_assembly:
        automatic_selection:
          - action: "Select core reviewers (code-quality, testing)"
            condition: "Always required for all tasks"
          - action: "Select specialized reviewers based on task type"
            condition: "Based on task analysis results"
          - action: "Validate reviewer availability and capabilities"
            condition: "Ensure selected reviewers can handle the task"
            
        manual_override:
          - action: "Check for manual reviewer specification"
            condition: "If --reviewers flag is provided"
            example: "*review TASK-001 --reviewers security,performance"
            
      review_strategy:
        - action: "Define parallel execution strategy"
        - action: "Set quality assessment priorities"
        - action: "Establish communication protocols"
    
    validation_checkpoint:
      - "Task type and complexity analyzed"
      - "Professional reviewer team assembled"
      - "Review strategy defined"
      - "Parallel execution plan ready"

  stage_2:
    id: 2
    name: "並行審查執行"
    name_en: "Parallel Review Execution"
    objectives:
      - "啟動所有專業reviewer進行並行審查"
      - "監控審查進度和狀態"
      - "處理審查過程中的問題"
    
    actions:
      reviewer_activation:
        core_reviewers:
          - action: "Activate task-reviewer:code-quality"
            purpose: "Code quality and architecture review"
            workflow: "unified-review-workflow.yaml"
            enforcement: "task-reviewer-enforcement.md"
            
          - action: "Activate task-reviewer:testing"
            purpose: "Testing coverage and strategy review"
            workflow: "unified-review-workflow.yaml"
            enforcement: "task-reviewer-enforcement.md"
            
        specialized_reviewers:
          - action: "Activate selected specialized reviewers"
            purpose: "Domain-specific quality review"
            workflow: "unified-review-workflow.yaml"
            enforcement: "task-reviewer-enforcement.md"
            
      parallel_execution:
        - action: "Execute all reviewers in parallel"
        - action: "Monitor execution progress and status"
        - action: "Handle any execution failures or timeouts"
        
      progress_monitoring:
        - action: "Track each reviewer's progress"
        - action: "Identify bottlenecks or issues"
        - action: "Ensure time synchronization across reviewers"
    
    parallelization:
      strategy: "All reviewers execute simultaneously"
      coordination: "Dr. Thompson monitors and coordinates"
      failure_handling: "Individual failures don't stop other reviewers"
      
    validation_checkpoint:
      - "All selected reviewers activated"
      - "Parallel execution started"
      - "Progress monitoring established"
      - "Failure handling protocols active"

  stage_3:
    id: 3
    name: "結果收集與整合"
    name_en: "Result Collection & Integration"
    objectives:
      - "收集所有reviewer的專業意見"
      - "整合和分析專業評估結果"
      - "解決reviewer之間的意見衝突"
    
    actions:
      result_collection:
        - action: "Collect results from all active reviewers"
        - action: "Validate result completeness and quality"
        - action: "Handle any missing or incomplete results"
        
      quality_assessment_integration:
        - action: "Integrate 7-dimension quality scores"
        - action: "Calculate weighted averages for each dimension"
        - action: "Identify score discrepancies and outliers"
        
      findings_integration:
        - action: "Merge findings from all reviewers"
        - action: "Remove duplicate findings"
        - action: "Resolve severity level conflicts"
        - action: "Prioritize findings by impact and urgency"
        
      recommendations_integration:
        - action: "Consolidate recommendations from all reviewers"
        - action: "Remove duplicate recommendations"
        - action: "Prioritize recommendations by feasibility and impact"
        - action: "Resolve conflicting recommendations"
        
      conflict_resolution:
        - action: "Identify conflicts between reviewer opinions"
        - action: "Apply Dr. Thompson's authority to resolve conflicts"
        - action: "Document resolution decisions and rationale"
        
      maturity_assessment:
        - action: "Calculate overall implementation maturity level"
        - action: "Determine Bronze/Silver/Gold/Platinum classification"
        - action: "Validate classification against quality thresholds"
    
    integration_strategy:
      scoring_aggregation: "Weighted average based on reviewer expertise"
      finding_consolidation: "Merge by issue type, keep highest severity"
      recommendation_prioritization: "By impact, feasibility, and effort"
      conflict_resolution: "Dr. Thompson's final authority"
      
    validation_checkpoint:
      - "All reviewer results collected"
      - "Quality assessment integrated"
      - "Findings consolidated and prioritized"
      - "Recommendations integrated and prioritized"
      - "Conflicts resolved"
      - "Maturity level determined"

  stage_4:
    id: 4
      name: "最終品質判斷"
      name_en: "Final Quality Decision"
      objectives:
        - "基於整合結果做出最終品質判斷"
        - "確定任務是否通過品質審查"
        - "設定後續行動和改進要求"
      
      actions:
        final_analysis:
          - action: "Review integrated quality assessment"
          - action: "Evaluate findings against quality standards"
          - action: "Assess risk and impact of identified issues"
          - action: "Consider business and technical constraints"
          
        decision_criteria:
          pass_criteria:
            - "All critical issues resolved or mitigated"
            - "Quality scores meet minimum thresholds"
            - "Implementation maturity level appropriate for task"
            - "No blocker or high-severity security issues"
            
          fail_criteria:
            - "Critical issues remain unresolved"
            - "Quality scores below minimum thresholds"
            - "Security vulnerabilities present"
            - "Core functionality not working"
            
        decision_making:
          - action: "Apply Dr. Thompson's quality judgment"
          - action: "Consider all evidence and expert opinions"
          - action: "Make final pass/fail decision"
          - action: "Document decision rationale"
          
        follow_up_planning:
          - action: "Define remediation requirements if failed"
          - action: "Set improvement priorities if passed"
          - action: "Plan follow-up review if needed"
          
      decision_authority:
        final_judgment: "Only Dr. Thompson can make final decision"
        override_capability: "Can override any reviewer recommendation"
        responsibility: "Full responsibility for decision quality"
        
      validation_checkpoint:
        - "Final quality analysis completed"
        - "Decision criteria evaluated"
        - "Final pass/fail decision made"
        - "Decision rationale documented"
        - "Follow-up plan defined"

  stage_5:
    id: 5
      name: "報告生成與維護"
      name_en: "Report Generation & Maintenance"
      objectives:
        - "根據模板生成最終審查報告"
        - "確保報告品質和完整性"
        - "維護報告的專業標準"
      
      actions:
        report_generation:
          - action: "Read report template from /Users/tszkinlai/Coding/AI workflow/core/qa/templates/review-tmpl.yaml"
          - action: "Generate comprehensive review report"
          - action: "Include all integrated findings and recommendations"
          - action: "Apply quality assessment and maturity classification"
          - action: "Ensure professional language and formatting"
          
        template_compliance:
          - action: "Follow report template structure exactly"
          - action: "Populate all required sections"
          - action: "Remove all placeholder values"
          - action: "Validate markdown formatting"
          
        evidence_integration:
          - action: "Include evidence from all reviewers"
          - action: "Provide specific file paths and line numbers"
          - action: "Include test results and metrics"
          - action: "Ensure traceability of all conclusions"
          
        quality_signature:
          - action: "Add Dr. Thompson's quality signature"
          - action: "Include final decision and rationale"
          - action: "Set review completion timestamp"
          - action: "Establish report authority"
          
        document_maintenance:
          - action: "Ensure report is complete and accurate"
          - action: "Validate all links and references"
          - action: "Check for any remaining issues"
          - action: "Prepare for stakeholder review"
          
      output_requirements:
        location: "{project_root}/docs/implementation-review/{task_id}-review.md(如`1-review.md`, `2-review.md`, `3-review.md`...)"
        format: "Professional markdown with proper structure"
        content: "Complete, evidence-based, actionable"
        authority: "Signed by Dr. Thompson"
        
      validation_checkpoint:
        - "Final report generated"
        - "Template compliance verified"
        - "All evidence integrated"
        - "Quality signature applied"
        - "Document maintenance completed"
        - "Report ready for delivery"

  stage_6:
    id: 6
      name: "任務狀態更新"
      name_en: "Task Status Update"
      depends_on: [5]
      objectives:
        - "根據最終審查結果更新任務狀態"
        - "同步更新相關文檔和元數據"
        - "完成審查流程的閉環"
      
      actions:
        task_status_update:
          - tool: "edit_file"
            target: "docs/specs/task.md"
            purpose: "Update task status based on review result"
            condition: "on_variable_value"
            variable_name: "final_review_status"
            
            on_value:
              pass:
                actions:
                  - action_type: "search_and_replace"
                    search_pattern: "- [ ] {task_id}"
                    replace_pattern: "- [x] {task_id}"
                  - action_type: "search_and_replace"
                    search_pattern: "- [ ] {sub_task_id}."
                    replace_pattern: "- [x] {sub_task_id}."
                  - action_type: "search_and_replace"
                    search_pattern: "QA狀態: .*"
                    replace_pattern: "QA狀態: 通過"
                  - action_type: "search_and_replace"
                    search_pattern: "審查文件: .*"
                    replace_pattern: "審查文件: {project_root}/docs/implementation-review/{task_id}-review.md(如`1-review.md`, `2-review.md`, `3-review.md`...)"
                  - action_type: "search_and_replace"
                    search_pattern: "審查時間: .*"
                    replace_pattern: "審查時間: {now_iso}"
                  - action_type: "search_and_replace"
                    search_pattern: "審查者: .*"
                    replace_pattern: "審查者: Dr. Thompson (Reviewer Orchestrator)"
                    
              fail:
                actions:
                  - action_type: "search_and_replace"
                    search_pattern: "- [ ] {task_id}"
                    replace_pattern: "- [-] {task_id}"
                  - action_type: "search_and_replace"
                    search_pattern: "QA狀態: .*"
                    replace_pattern: "QA狀態: 失敗"
                  - action_type: "search_and_replace"
                    search_pattern: "審查文件: .*"
                    replace_pattern: "審查文件: {project_root}/docs/implementation-review/{task_id}-review.md(如`1-review.md`, `2-review.md`, `3-review.md`...)"
                  - action_type: "search_and_replace"
                    search_pattern: "審查時間: .*"
                    replace_pattern: "審查時間: {now_iso}"
                  - action_type: "search_and_replace"
                    search_pattern: "審查者: .*"
                    replace_pattern: "審查者: Dr. Thompson (Reviewer Orchestrator)"
                    
        metadata_synchronization:
          - action: "Update task completion status"
          - action: "Synchronize review document references"
          - action: "Update review timestamps"
          - action: "Ensure consistency across all documents"
          
        process_completion:
          - action: "Verify all updates completed successfully"
          - action: "Confirm review process closure"
          - action: "Prepare for next review cycle"
          
      validation_checkpoint:
        - "Task status updated successfully"
        - "Metadata synchronized"
        - "Process completion verified"
        - "Review cycle closed"

critical_success_factors:
  mandatory_requirements:
    orchestration_authority:
      description: "Dr. Thompson has final authority over all review decisions"
      includes:
        - "Reviewer team assembly"
        - "Parallel execution coordination"
        - "Result integration and conflict resolution"
        - "Final quality judgment"
        - "Report maintenance"
        
    parallel_execution:
      description: "All reviewers execute simultaneously for efficiency"
      enforcement: "Coordinate parallel execution while maintaining quality"
      
    unified_standards:
      description: "All reviewers follow unified quality framework"
      validation_required: true
      
    evidence_based_decisions:
      description: "All conclusions supported by concrete evidence"
      validation_required: true
      
    professional_quality:
      description: "Maintain highest professional standards in all outputs"
      validation_required: true

  error_handling:
    reviewer_failure_protocol:
      steps:
        - "Assess failure impact on overall review"
        - "Continue with available reviewers if possible"
        - "Escalate to manual review if critical"
        - "Document failure and recovery actions"
        
    coordination_failure_protocol:
      steps:
        - "Identify coordination failure point"
        - "Implement fallback coordination strategy"
        - "Ensure review completion despite issues"
        - "Document lessons learned for improvement"

  quality_gates:
    requirements:
      - "All stages completed sequentially"
      - "Professional reviewer team properly assembled"
      - "Parallel execution coordinated successfully"
      - "Results integrated without conflicts"
      - "Final decision made with full authority"
      - "Report generated and maintained professionally"
      - "Task status updated accurately"
    
    success_criteria: "Comprehensive, coordinated review with professional quality output"

# Tool Integration Guidelines
tool_usage_patterns:
  file_operations:
    read_file: "Use for reading specific known files"
    glob_file_search: "Use for pattern-based file discovery"
    list_dir: "Use for directory exploration"
    
  code_analysis:
    codebase_search: "Use for semantic code understanding"
    grep: "Use for pattern matching and exact text search"
    
  documentation:
    write: "Use for generating final reports"
    search_replace: "Use for updating existing documents"

# AI Processing Notes
ai_optimization:
  structured_format: "YAML enables better parsing and validation"
  clear_hierarchy: "Nested structure maps to AI decision trees"
  tool_integration: "Explicit tool calls reduce AI confusion"
  validation_points: "Checkpoints enable early error detection"
  parallel_execution: "Coordinate multiple reviewers simultaneously"
  authority_clear: "Dr. Thompson has final decision authority"
