name: Create Architecture Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Configure environment (.env)
        run: |
          cat > .env << 'EOF'
          PROMPTFOO_PROVIDER=${{ secrets.PROMPTFOO_PROVIDER }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}
          GOOGLE_VERTEX_PROJECT=${{ secrets.GOOGLE_VERTEX_PROJECT }}
          GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          HTTP_PROXY=${{ secrets.HTTP_PROXY }}
          HTTPS_PROXY=${{ secrets.HTTPS_PROXY }}
          EOF

      - name: Run create-architecture tests
        run: npm run test:create-architecture

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: create-architecture-${{ github.run_id }}
          path: artifacts/create-architecture

